M48
; DRILL file {KiCad 8.0.8} date 2025-02-16T12:09:59-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-16T12:09:59-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0453
%
G90
G05
T1
X4.298Y-4.2087
T2
X5.1575Y-2.8524
M30
