M48
; DRILL file {KiCad 8.0.8} date 2025-02-12T10:11:09-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-12T10:11:09-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X4.298Y-4.2087
T2
X4.4685Y-2.8476
X4.5866Y-2.8476
M30
